empmgmt/empmgmt/Controllers/EmployeeController.cs
using ClosedXML.Excel;
using empmgmt.Data;
using empmgmt.Extension;
using empmgmt.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Data.OleDb;

namespace empmgmt.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IConfiguration configuration;
        bool IsSessionExpired = false;
        public EmployeeController(AppDBContext context, IConfiguration configuration)
        {
            this._context = context;
            this.configuration = configuration;
        }

        [HttpPost]
        public async Task<IActionResult> FileImport(IFormFile execlFile)
        {
            if (execlFile != null)
            {
                string path = Path.Combine(AppContext.BaseDirectory, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string fileName = Path.GetFileName(execlFile.FileName);
                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    execlFile.CopyTo(stream);
                }
                string ExcelConnString = configuration.GetConnectionString("ExcelConString");

                DataTable dt = new DataTable();
                ExcelConnString = string.Format(ExcelConnString, filePath);

                using (OleDbConnection connExcel = new OleDbConnection(ExcelConnString))
                {
                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {
                            cmdExcel.Connection = connExcel;

                            connExcel.Open();
                            DataTable? dtExcelSchema;
                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

                            string? sheetName = String.Empty;
                            if (dtExcelSchema != null && dtExcelSchema.Rows.Count > 0)
                                if (dtExcelSchema.Columns.Contains("TABLE_NAME"))
                                    sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            connExcel.Close();

                            if (!string.IsNullOrEmpty(sheetName))
                            {
                                connExcel.Open();
                                cmdExcel.CommandText = "Select [Employee Id] as emp_id, [Employee Name] as emp_name,[Date of Birth] as date_of_birth,[Joining Date] as joining_date,[Skills] as skills,[Salary] as salary,[Designation] as designation,[Email] as email_id From [" + sheetName + "]";
                                odaExcel.SelectCommand = cmdExcel;
                                odaExcel.Fill(dt);
                                connExcel.Close();
                            }
                        }
                    }
                }

                if (dt != null && dt.Rows.Count > 0)
                {
                    SqlParameter p1 = new SqlParameter("@emp", dt);
                    p1.TypeName = "dbo.tt_employee";
                    p1.SqlDbType = SqlDbType.Structured;

                    SqlParameter[] sqlParams = new SqlParameter[] { p1 };
                    string strParams = string.Join(',', sqlParams.Select(x => x.ParameterName).ToArray());
                    await _context.Database.ExecuteSqlRawAsync($"sp_employee_ins_upd_bulk {strParams}", sqlParams);
                }
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IsSessionExpired = string.IsNullOrEmpty(HttpContext?.Session?.GetString("username"));
            if (IsSessionExpired)
                return RedirectToAction("Index", "Home");

            var emp = await _context.view_employee.ToListAsync();
            return View(emp);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var emp = await _context.employee.FirstOrDefaultAsync(x => x.emp_id == id);
            if (Equals(emp, null))
                return RedirectToAction("Index");

            _context.employee.Remove(emp);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddUpdate(int id = 0)
        {
            if (Equals(id, 0))
                return View();

            var emp = await _context.view_employee.FirstOrDefaultAsync(x => x.emp_id == id);
            if (Equals(emp, null))
                return RedirectToAction("Index");

            EmployeeViewModel employee = new EmployeeViewModel
            {
                emp_id = emp.emp_id,
                emp_name = emp.emp_name,
                date_of_birth = emp.date_of_birth,
                joining_date = emp.joining_date,
                designation = emp.designation,
                salary = emp.salary,
                skills = emp.skills,
                email_id = emp.email_id
            };

            return View(employee);
        }

        [HttpPost]
        public async Task<IActionResult> AddUpdate(EmployeeViewModel employeeRequest)
        {
            SqlParameter[] sqlParams = new SqlParameter[]
            {
                new SqlParameter("@emp_id", employeeRequest.emp_id),
                new SqlParameter("@emp_name",employeeRequest.emp_name),
                new SqlParameter("@date_of_birth",employeeRequest.date_of_birth),
                new SqlParameter("@joining_date",employeeRequest.joining_date),
                new SqlParameter("@designation",employeeRequest.designation),
                new SqlParameter("@salary",employeeRequest.salary),
                new SqlParameter("@email_id",employeeRequest.email_id),
                new SqlParameter("@skills",employeeRequest.skills)
            };
            string strParams = string.Join(',', sqlParams.Select(x => x.ParameterName).ToArray());
            await _context.Database.ExecuteSqlRawAsync($"sp_employee_ins_upd {strParams}", sqlParams);

            return RedirectToAction("index");
        }

        [HttpPost]
        public async Task<IActionResult> Export()
        {
            DataTable dt = new DataTable("emp");
            var emp = await _context.employee.ToListAsync();
            if (emp != null)
                dt = emp.ToDataTable();

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Employee.xlsx");
                }
            }
        }
    }
}

empmgmt/empmgmt/Controllers/SkillController.cs
using empmgmt.Data;
using empmgmt.Models;
using empmgmt.Models.db;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace empmgmt.Controllers
{
    public class SkillController : Controller
    {
        private readonly AppDBContext _context;

        public SkillController(AppDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var skill = await _context.skills.ToListAsync();
            return View(skill);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(SkillViewModel skillPayload)
        {
            skills skill = new skills
            {
                name = skillPayload.name
            };
            await _context.skills.AddAsync(skill);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var skill = await _context.skills.FirstOrDefaultAsync(x => x.id == id);
            if (Equals(skill, null))
                return RedirectToAction("Index");

            SkillViewModel skillView = new SkillViewModel
            {
                id = skill.id,
                name = skill.name
            };

            return View(skillView);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SkillViewModel skillPayload)
        {
            skills skill = new skills
            {
                id = skillPayload.id,
                name = skillPayload.name
            };
            _context.skills.Update(skill);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var skill = await _context.skills.FirstOrDefaultAsync(x => x.id == id);
            if (Equals(skill, null))
                return RedirectToAction("Index");

            _context.skills.Remove(skill);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

empmgmt/empmgmt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/empmgmt.styles.css" asp-append-version="true" />*@
</head>
<body>
    <script src="~/lib/js/all.min.js"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">empmgmt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="Index">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employee Management System
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

empmgmt/empmgmt/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript">
        $("#img-captcha").click(function (event) {
            event.preventDefault();
            resetCaptchaImage();
        });

        function resetCaptchaImage() {
            d = new Date();
            $("#img-captcha").attr("src", "/get-captcha-image?" + d.getTime());
        }
    </script>
</body>
</html>